# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReserveFilm():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reserveFilm(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(982, 1050)
    self.driver.find_element(By.LINK_TEXT, "Evenementen en Films").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-6:nth-child(2) .bg-white").click()
    self.driver.find_element(By.LINK_TEXT, "Reserveren").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("naam")
    self.driver.find_element(By.NAME, "email").send_keys("email")
    self.driver.find_element(By.NAME, "address").send_keys("adres")
    self.driver.find_element(By.NAME, "postal_code").send_keys("AAAA11")
    self.driver.find_element(By.NAME, "city").send_keys("stad")
    self.driver.find_element(By.ID, "663").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .bg-white").click()
  
