# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExportEventReservation():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_exportEventReservation(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(982, 1050)
    self.driver.find_element(By.LINK_TEXT, "Evenementen en Films").click()
    self.driver.find_element(By.LINK_TEXT, "+Info").click()
    self.driver.find_element(By.LINK_TEXT, "Reserveren (NL)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("naam")
    self.driver.find_element(By.NAME, "email").send_keys("email")
    self.driver.find_element(By.NAME, "address").send_keys("adres")
    self.driver.find_element(By.NAME, "postal_code").send_keys("AAAA11")
    self.driver.find_element(By.NAME, "city").send_keys("stad")
    self.driver.find_element(By.NAME, "ticket_number").click()
    self.driver.find_element(By.NAME, "ticket_number").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-200").click()
    self.driver.find_element(By.ID, "file").send_keys("C:\\fakepath\\joker.png")
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .bg-white").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-12").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.CSS_SELECTOR, ".px-4").click()
    self.driver.find_element(By.LINK_TEXT, "Evenementreservaties").click()
    self.driver.find_element(By.LINK_TEXT, "Export naar JSON").click()
    self.driver.find_element(By.LINK_TEXT, "Log uit").click()
  
