# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateUpdateDeleteEvent():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createUpdateDeleteEvent(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(982, 1050)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.CSS_SELECTOR, ".px-4").click()
    self.driver.find_element(By.LINK_TEXT, "Evenementen en Films").click()
    self.driver.find_element(By.LINK_TEXT, "+Evenement aanmaken").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("titel")
    self.driver.find_element(By.NAME, "description").send_keys("beschrijving")
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("0titel")
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("0beschrijving")
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("adres")
    self.driver.find_element(By.NAME, "city").send_keys("stad")
    self.driver.find_element(By.NAME, "max_tickets").send_keys("10")
    self.driver.find_element(By.NAME, "price").send_keys("10")
    self.driver.find_element(By.NAME, "start_date").click()
    self.driver.find_element(By.NAME, "start_date").send_keys("2021-05-11T16:34")
    self.driver.find_element(By.NAME, "end_date").click()
    self.driver.find_element(By.NAME, "end_date").send_keys("2021-05-11T17:34")
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .bg-white").click()
    self.driver.find_element(By.LINK_TEXT, "+Info").click()
    self.driver.find_element(By.LINK_TEXT, "Bewerken").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("0titel1")
    self.driver.find_element(By.CSS_SELECTOR, ".col-span-2").click()
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("0beschrijving1")
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("adres1")
    self.driver.find_element(By.NAME, "city").click()
    self.driver.find_element(By.NAME, "city").send_keys("stad1")
    self.driver.find_element(By.NAME, "max_tickets").click()
    self.driver.find_element(By.NAME, "max_tickets").send_keys("101")
    self.driver.find_element(By.NAME, "price").click()
    self.driver.find_element(By.NAME, "price").send_keys("101")
    self.driver.find_element(By.NAME, "start_date").click()
    self.driver.find_element(By.NAME, "start_date").send_keys("2021-05-12T16:34")
    self.driver.find_element(By.NAME, "end_date").click()
    self.driver.find_element(By.NAME, "end_date").send_keys("2021-05-12T17:34")
    self.driver.find_element(By.CSS_SELECTOR, ".py-12").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .bg-white").click()
    self.driver.find_element(By.LINK_TEXT, "+Info").click()
    self.driver.find_element(By.LINK_TEXT, "Bewerken").click()
    self.driver.find_element(By.LINK_TEXT, "Verwijderen").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-red-500").click()
    self.driver.find_element(By.LINK_TEXT, "Log uit").click()
  
